version: "3.9"

services:
  tester:
    image: naxim/simple-vpn-dev
    container_name: simple_vpn_dev_tester
    environment:
      - PYLINTRC=/data/test/pylint/pylintrc
    volumes:
      - ${DATA_PATH}/:/data/
    command: >
      bash -c " \
      chmod +x test/pylint/script.sh && \
      test/pylint/script.sh "

  openssl:
    image: alpine/openssl
    container_name: simple_vpn_dev_openssl
    environment:
      - nginx_host=${NGINX_HOST:-wireguard.local}
    volumes:
      - ${DATA_PATH}/:/data/
      - certbot:/data/private/ssl
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/data/docker/dev/generate_selfsigned_cert.sh"]

volumes:
  certbot:
