FROM alpine

RUN apk update && apk upgrade

RUN apk add --no-cache --update \
 curl \
 wget \
 which \
 jq \
 bash \
 python3 \
 py3-pip \
 git \
 npm

RUN pip install pylint

RUN npm install -g eslint eslint-config-airbnb-base eslint-plugin-import eslint/create-config

RUN mkdir /data

WORKDIR /data