FROM alpine

RUN apk update && apk upgrade

RUN apk add --no-cache --update \
 curl \
 wget \
 which \
 jq \
 bash \
 make \
 docker \
 docker-cli-compose

RUN tf_release=`curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest |  grep tag_name | cut -d: -f2 | tr -d \"\,\v | awk '{$1=$1};1'` && \
wget https://releases.hashicorp.com/terraform/${tf_release}/terraform_${tf_release}_linux_amd64.zip -O /tmp/terraform.zip && \
unzip /tmp/terraform.zip && \
rm -f /tmp/terraform.zip && \
mv terraform /usr/bin/terraform

RUN mkdir /simple-vpn

WORKDIR /simple-vpn

ENTRYPOINT ["make"]

CMD ["help"]