version: "3.9"
services:
  terraform:
    # image: hashicorp/terraform
    image: naxim/vpn_utils
    container_name: terraform
    volumes:
      - ../terraform/:/terraform/:rw
      - ../private/:/private/:ro
    working_dir: /terraform
    entrypoint: sh