version: "3.9"
services:
  simple_vpn_builder:
    image: naxim/simple-vpn-builder
    container_name: simple_vpn_builder
    volumes:
      - ../:/simple-vpn/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    command: "install"