ARG terraform_version=latest

FROM hashicorp/terraform:$terraform_version

ARG python_version="3.6.9-r3 --repository=http://dl-cdn.alpinelinux.org/alpine/v3.9/main"

RUN apk update && apk upgrade
RUN echo $python_version
RUN apk add --update \
 python3=${python_version} \
 curl \
 which \
 bash
RUN curl -sSL https://sdk.cloud.google.com | bash
ENV PATH $PATH:/root/google-cloud-sdk/bin