version: "3.9"

services:
  webuiapp:
    image: tiangolo/uwsgi-nginx:${VER_PY:-python3.9}
    container_name: wireguard_webuiapp
    volumes:
      - ../../wireguard_configs:/wireguard_configs
      - ../../webui:/app:r
      - /app/static/design-src
      - webuiapp_pycache1:/app/.cache
      - webuiapp_pycache2:/app/__pycache__
      - webuiapp_data:/app/data/
      - webuiapp_pycache:/usr/local/lib/${VER_PY:-python3.9}/site-packages
    environment:
      - UWSGI_CHEAPER ${UWSGI_CHEAPER:-1}
      - UWSGI_PROCESSES ${UWSGI_PROCESSES:-4}

  balancer:
    image: nginx:mainline-alpine-slim
    container_name: wireguard_balancer
    environment:
      - NGINX_HOST=${NGINX_HOST:-wireguard.local}
      - NGINX_DOCKER_HOST_IP=${NGINX_DOCKER_HOST_IP:-'192.168.1.1'}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT:-80}
    volumes:
      - ../../nginx:/etc/nginx/
      - balancer_conf_d:/etc/nginx/conf.d
      - certbot:/etc/nginx/ssl:ro
      - ../../webui/static:/app:r
      - /app/design-src
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443

  certbot:
    image: certbot/certbot:latest
    container_name: wireguard_certbot
    environment:
      - NGINX_HOST=${NGINX_HOST:-wireguard.local}
      - EMAIL=${EMAIL}
    volumes:
      - certbot:/etc/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./wireguard_balancer_reload.py:/opt/certbot/wireguard_balancer_reload.py
      - ../../logs:/var/log/letsencrypt
      - ./renew_certs_cron:/etc/periodic/15min/renew_certs_cron
    entrypoint: ["crond", "-f"]


volumes:
  webuiapp_data:
  webuiapp_pycache: 
  webuiapp_pycache1:
  webuiapp_pycache2:
  balancer_conf_d:
  certbot: