name: Launch pylint

on:
  push:
    branches:
      - cicd

jobs:
  test-py-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Prepare for tests
        run: ls -la
      
      - name: Start linter
        run: |
          DATA_PATH='../..' docker compose -p wireguard -f docker/dev/docker-compose.yml run --rm tester pylint webui
          
