name: Launch pylint

on:
  push:
    branches:
      - cicd

jobs:
  test-py-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          fetch-depth: 2
      
      - name: Start linter
        run: |
          DATA_PATH='..' docker compose -p wireguard -f ./docker/docker-compose.yml run --rm simple_vpn_builder test
          
