name: Launch pylint

on:
  push:
    branches:
      - cicd

jobs:
  test-py-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          fetch-depth: 2
      
      - name: Start linter
        run: |
          ls -la && \
          DATA_PATH='../..' docker compose -p wireguard -f docker/dev/docker-compose.yml run --entrypoint ls --rm tester -la test/pylint && \
          DATA_PATH='../..' docker compose -p wireguard -f docker/dev/docker-compose.yml run --rm tester
          
