name: tests

on:
  push:
    branches:
      - cicd

jobs:
  launch-linters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          fetch-depth: 2
      
      - name: Start linters
        run: |
          DATA_PATH='..' docker compose -p wireguard -f ./docker/docker-compose.yml run --rm simple_vpn_builder test
  
  test-deploy:
    needs: [launch-linters]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          fetch-depth: 2
      - name: Add wireguard.local to hosts
        run: |
          addr=`ip -4 addr show docker0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'` && \
          echo -e '127.0.0.1\twireguard.local' | sudo tee -a /etc/hosts 1>/dev/null && \
          echo -e $addr'\thost.docker.internal' | sudo tee -a /etc/hosts
      - name: Start test-deploy
        run: |
          DATA_PATH='..' docker compose -p wireguard -f ./docker/docker-compose.yml run --rm simple_vpn_builder install-auto-test   
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: webui.db
          path: webui/data/webui.db
