name: test-deploy

on:
  push:
    branches:
      - cicd

jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          set-safe-directory: '*'
          fetch-depth: 2
      - name: Add wireguard.local to hosts
        run: |
          echo -e '127.0.0.1\twireguard.local' | sudo tee -a /etc/hosts 1>/dev/null
      - name: Start test-deploy
        run: |
          DATA_PATH='..' docker compose -p wireguard -f .\docker\docker-compose.yml run --rm -ti simple_vpn_builder install-auto-test
